"""add projects and capture_events tables

Revision ID: bd4354d33248
Revises: 006_memory_consolidation
Create Date: 2026-08-26 01:01:21.336909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4354d33248'
down_revision: Union[str, None] = '006_memory_consolidation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('canonical_path', sa.String(length=1024), nullable=False),
    sa.Column('git_root', sa.String(length=1024), nullable=True),
    sa.Column('remote_url', sa.String(length=1024), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('discovered', 'connected', 'memorized', 'active', 'disabled', name='project_status', native_enum=False), nullable=False),
    sa.Column('capture_enabled', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_path'),
    sa.UniqueConstraint('namespace')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_canonical_path', ['canonical_path'], unique=True)
        batch_op.create_index('ix_projects_last_activity', ['last_activity_at'], unique=False)
        batch_op.create_index('ix_projects_namespace', ['namespace'], unique=True)
        batch_op.create_index('ix_projects_status', ['status'], unique=False)

    op.create_table('capture_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('git', 'filesystem', 'codex', 'kilo', 'opencode', 'generic', 'manual', name='capture_source', native_enum=False), nullable=False),
    sa.Column('source_event_type', sa.Enum('project_discovered', 'git_commit', 'git_branch_change', 'file_batch_changed', 'agent_session_started', 'agent_session_finished', 'agent_summary', 'agent_decision', 'agent_tool_result', 'manual_note', name='capture_event_type', native_enum=False), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('working_directory', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=512), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='capture_processing_status', native_enum=False), nullable=False),
    sa.Column('memory_event_id', sa.String(length=36), nullable=True),
    sa.Column('memory_id', sa.String(length=36), nullable=True),
    sa.Column('admission_decision', sa.Enum('store', 'ignore', name='admission_decision', native_enum=False), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    with op.batch_alter_table('capture_events', schema=None) as batch_op:
        batch_op.create_index('ix_capture_events_fingerprint', ['fingerprint'], unique=True)
        batch_op.create_index('ix_capture_events_memory_id', ['memory_id'], unique=False)
        batch_op.create_index('ix_capture_events_namespace', ['namespace'], unique=False)
        batch_op.create_index('ix_capture_events_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_capture_events_processing_status', ['processing_status'], unique=False)
        batch_op.create_index('ix_capture_events_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_capture_events_source', ['source'], unique=False)

    with op.batch_alter_table('memory_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_embeddings_provider_model'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_embeddings_provider_model'), ['provider', 'model_name', 'dimension'], unique=False)

    with op.batch_alter_table('capture_events', schema=None) as batch_op:
        batch_op.drop_index('ix_capture_events_source')
        batch_op.drop_index('ix_capture_events_project_id')
        batch_op.drop_index('ix_capture_events_processing_status')
        batch_op.drop_index('ix_capture_events_occurred_at')
        batch_op.drop_index('ix_capture_events_namespace')
        batch_op.drop_index('ix_capture_events_memory_id')
        batch_op.drop_index('ix_capture_events_fingerprint')

    op.drop_table('capture_events')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_status')
        batch_op.drop_index('ix_projects_namespace')
        batch_op.drop_index('ix_projects_last_activity')
        batch_op.drop_index('ix_projects_canonical_path')

    op.drop_table('projects')
    # ### end Alembic commands ###
